### ISSUE TITLE
Powered OGN traffic seems filtered

### ISSUE THREAD

**Issue by avia-tion-ca** [Meisterschueler/ogn-viewer-android#30]
Powered flight schools near my gliderport are using NemoScout tracking devices, and NemoScout is feeding their position data in to OGN so that the NemoScout aircraft are visible on http://live.glidernet.org/ in blue.  

These aircraft do not seem to appear in OGN Viewer, and so this power traffic in our area does not get picked up on the moving map display in XCSoar when using OGN Viewer with the FLARM driver.  Could the display of this power traffic be enabled with an app configuration setting?

![image](https://user-images.githubusercontent.com/67653342/86159567-88db5800-bad8-11ea-9773-f33cf8d70cfb.png)

**Comment by Meisterschueler** [comment]
The packet from APRS string is this:

`C-GPZT>APRS,qAS,CYFD2:/174032h4324.77N/08011.32W'135/076/A=002551 !W16! id21C06EE2 +663fpm +0.0rot 11.0dB 0e 0.0kHz gps3x5`

Seems that the NemoScout device uses the old APRS format. @avia-tion-ca: could you please double check you APRS filter settings?

**Comment by avia-tion-ca** [comment]
Good morning!  Sorry it took a while to respond, I'm a little slow these days.

I double-checked my APRS settings as best I know how, and I tried both the "moving" and manual styles.  None of my attempts in reconfiguring the APRS filter would let me see the NemoScout traffic.

Screenshots: https://photos.app.goo.gl/qiFpUjc6aGoZqHXLA

Would it be possible for OGN Viewer to see traffic that is uploading the "Old" APRS format, or will the NemoScout developer have to update his stuff to publish with the "New" APRS format?  

Is there a link or documentation on the "Old" and "New" APRS formats that I could reference when reporting this defect to the NemoScout developer?

Thanks!

**Comment by avia-tion-ca** [comment]
As of today, the NemoScout developer has completed the necessary updates for this traffic to appear correctly in the OGN Viewer, thanks!
