### ISSUE TITLE
Flight paths (tracks) do not load / show anymore

### ISSUE THREAD

**Issue by csindle** [Meisterschueler/ogn-viewer-android#37]
The "Flight Path" feature seems not to be working anymore, regardless of type ("Standard" or "Multicolor (slower)" ).  Multiple users report the same issue.

This started around 2022Q4.

It is a very useful feature for both pilots and observers.

Thank you.

**Comment by prikril** [comment]
Hi @csindle 
Thanks for creating this issue!
It was a backend problem since 2022-11-12 with unkown reason.
I restarted the service and the flight path feature should be working again now.
Dominik

@Meisterschueler Please close this issue.

**Comment by Meisterschueler** [comment]
@prikril Thank you

**Comment by tpatja** [comment]
Hi @prikril, @Meisterschueler,

The flight paths have not been working again for the past few days, regardless of type. Could be the same backend problem.. can you try restarting it again, please?

Thanks.
