### ISSUE TITLE
Feature Request: Add a setting to change altitude units to feet

### ISSUE THREAD

**Issue by csindle** [Meisterschueler/ogn-viewer-android#8]
![ognv](https://user-images.githubusercontent.com/190719/36642698-39733b04-1a4c-11e8-883a-68406ca1aeec.png)

Many countries still use feet to measure a planes altitude.
This request is for a setting to change the altitude display units from metres to feet.

( 1 metre = 3,28084 feet.  :smiley:  )

One can imagine that _others_ may also want to change the `gs` and `vs` units...

Thanks for a very useful app!

**Comment by prikril** [comment]
Hi,
I am glad that you like the app.
It would be nice if you rate the app at the play store.
Thank you.

Feature Request: adjustable units
Ok, you are right.
Should be easy to implement...
I will add these three settings to one of the next versions and inform you here.
Like this way?
-altitude in meters and feet
-groud speed in km/h, mph and knots
-vertical speed in m/s and fpm
Should the unit of receiver altitude also be adjustable?

Greets
Dominik

**Comment by csindle** [comment]
Hi Dominik,

Yes, those units sound great.

> Should the unit of receiver altitude also be adjustable?

I would think that one altitude setting should affect both aircraft, and receivers. :thinking: 

I'm an "Beta Tester" for this app, so cannot rate it, sorry.  :confused: 

Thank you very much.

---
FYI: Winch drivers find this app very useful to get the height of each launch. :thumbsup:

**Comment by prikril** [comment]
Alright, no problem.

Ok, altitude setting will affect aircraft and receivers.
I think you can test this feature soon in a beta version.

It's interesting to hear that there are many different purposes of this app to help people.

**Comment by prikril** [comment]
Hi @csindle,
the new settings to change units were added some days ago in the beta version of V 1.3.6
I hope you are satisfied?
An other thing that I changed is the position of the info window from aircraft markers.
Your screenshot shows the problem, when aircraft rotation is more then +-90 degree:
The info window will hide the aircraft marker.
I fixed that in the final version of V 1.3.6
It will be released in the next days.

**Comment by csindle** [comment]
Hi Dominik,

This looks great. Thank you very much.
I'm also loving TCP Flarm server when collecting to TopHat/ XC Soar.

Thanks again,

Colin.

**Comment by prikril** [comment]
Thanks for your positive feedback.
This issue will be closed after release of 1.3.6

**Comment by Meisterschueler** [comment]
Fixed with acbdd55db10c267616109b4a2e9d7dc20fed4251
