### ISSUE TITLE
Feature Request: Position based filter with auto-update

### ISSUE THREAD

**Issue by Meisterschueler** [Meisterschueler/ogn-viewer-android#9]
You can use the OGN viewer as adapter for XCSoar or another navigational software. For this a automatic update of the position based filter would be good.
Some ideas:
1. default radius could be 25km or smaller
2. since a change of the aprs filter causes a reconnect the changes should depend on the distance to the last change. In other words: position update only if the distance to the current filter is > 5km

**Comment by snip** [comment]
+1

**Comment by prikril** [comment]
Hi,
I think some users would like to have an auto-update position based radius filter too.
But I will have no time in the next 2-3 months to implement it  and I don't need this function.
Just some of my ideas how this could be implemented:

- Get the users current position and create an APRS radius filter.
- Create a geofence that is smaller than the radius of the APRS filter. (https://developer.android.com/training/location/geofencing)
- Trigger the "exit" event of the geofence.
- If triggered, change get the new current position, change the APRS radius filter, delete the old geofence and create a new geofence.

Two new settings could be added to prefs fragment:

- Auto update position (on-off switch / checkbox)
- Auto update radius in kilometers (dropdown / text field)

The geofence service should be well tested to verify that the "exit" is triggered in time.
Maybe it helps if the position is refreshed periodically as it is implemented for the TCP server.

Things to discuss:

- Overwrite current APRS filter? Or just a part of it?
- How to combine with https://github.com/Meisterschueler/ogn-viewer-android/issues/16?
- Minimum/Maximum for geofence radius?
